name: MSBuild-D2RLauncher

on:
  push:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild and Windows SDK
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '17.12'

    - name: Set Windows SDK Paths
      run: |
        echo "LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\um\x64" >> $GITHUB_ENV
        echo "INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\shared;C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt" >> $GITHUB_ENV

    - name: Restore and Build
      run: |
        nuget restore ${{ env.SOLUTION_FILE_PATH }}
        msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=x64 ${{ env.SOLUTION_FILE_PATH }}

    - name: Download handle64.exe
      run: |
        Invoke-WebRequest -Uri "https://download.sysinternals.com/files/Handle.zip" -OutFile "Handle.zip"
        Expand-Archive -Path "Handle.zip" -DestinationPath "handle_temp"
        mkdir "x64\${{ env.BUILD_CONFIGURATION }}" -Force
        Move-Item -Path "handle_temp\handle64.exe" -Destination "x64\${{ env.BUILD_CONFIGURATION }}\handle64.exe" -Force

    - name: Package and Release
      run: |
        mkdir D2RLauncher
        Copy-Item -Path "x64\${{ env.BUILD_CONFIGURATION }}\D2RLauncher.exe" -Destination "D2RLauncher\"
        Copy-Item -Path "x64\${{ env.BUILD_CONFIGURATION }}\handle64.exe" -Destination "D2RLauncher\"
        Compress-Archive -Path D2RLauncher\* -DestinationPath D2RLauncher.zip
        echo "RELEASE_FILE=D2RLauncher.zip" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.RELEASE_FILE }}
        tag_name: latest
        release_name: Latest Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
