name: MSBuild-D2RLauncher

on:
  push:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install DirectX SDK
      run: choco install directx-sdk --ignore-checksums -y

    - name: Discover DirectX SDK Installation Path
      id: discover_dx_sdk
      shell: powershell
      run: |
        $dxSdkPath = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\DirectX' -Name 'InstallationFolder' -ErrorAction SilentlyContinue).InstallationFolder
        if (-not $dxSdkPath) {
          # Fallback to Chocolatey's default install location if registry key is missing
          $dxSdkPath = "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)"
        }
        if (-not (Test-Path $dxSdkPath)) {
          Write-Error "DirectX SDK not found at $dxSdkPath. Installation may have failed."
          exit 1
        }
        echo "DXSDK_DIR=$dxSdkPath" >> $GITHUB_ENV
        echo "LIB=$dxSdkPath\Lib\x86" >> $GITHUB_ENV  # Use x86 unless your app is explicitly 64-bit
        echo "INCLUDE=$dxSdkPath\Include" >> $GITHUB_ENV
        echo "Found DirectX SDK at: $dxSdkPath"

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet Packages
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Build Solution
      run: |
        # Explicitly pass environment variables to MSBuild
        msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:DXSDK_DIR="${{ env.DXSDK_DIR }}" /p:Lib="${{ env.LIB }}" /p:Include="${{ env.INCLUDE }}" ${{ env.SOLUTION_FILE_PATH }}
      shell: cmd

    - name: Download handle64.exe
      run: |
        Invoke-WebRequest -Uri "https://download.sysinternals.com/files/Handle.zip" -OutFile "Handle.zip"
        Expand-Archive -Path "Handle.zip" -DestinationPath "handle_temp"
        Move-Item -Path "handle_temp\handle64.exe" -Destination "bin\${{ env.BUILD_CONFIGURATION }}\" -Force

    - name: Package Executable and Dependencies
      run: |
        mkdir D2RLauncher
        Copy-Item -Path "bin\${{ env.BUILD_CONFIGURATION }}\D2RLauncher.exe" -Destination "D2RLauncher\" -Force
        Copy-Item -Path "bin\${{ env.BUILD_CONFIGURATION }}\handle64.exe" -Destination "D2RLauncher\" -Force
        Compress-Archive -Path D2RLauncher\* -DestinationPath D2RLauncher.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: D2RLauncher.zip
        tag_name: latest
        release_name: Latest Release
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
