name: MSBuild-D2RLauncher

on:
  push:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install DirectX SDK
      run: choco install directx-sdk --ignore-checksums -y

    - name: Set DirectX SDK paths
      run: |
        echo "DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)" >> $GITHUB_ENV
        echo "LIB=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Lib\x64" >> $GITHUB_ENV
        echo "INCLUDE=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Include" >> $GITHUB_ENV

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet Packages
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Build Solution
      run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE_PATH }}

    - name: Download handle64.exe
      run: |
        Invoke-WebRequest -Uri "https://download.sysinternals.com/files/Handle.zip" -OutFile "Handle.zip"
        Expand-Archive -Path "Handle.zip" -DestinationPath "handle_temp"
        Move-Item -Path "handle_temp\handle64.exe" -Destination "bin\${{ env.BUILD_CONFIGURATION }}\" -Force

    - name: Package Executable and Dependencies
      run: |
        mkdir D2RLauncher
        Copy-Item -Path "bin\${{ env.BUILD_CONFIGURATION }}\D2RLauncher.exe" -Destination "D2RLauncher\" -Force
        Copy-Item -Path "bin\${{ env.BUILD_CONFIGURATION }}\handle64.exe" -Destination "D2RLauncher\" -Force
        Compress-Archive -Path D2RLauncher\* -DestinationPath D2RLauncher.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: D2RLauncher.zip
        tag_name: latest
        release_name: Latest Release
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
